name: Sync Jetpack Data

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write  # Required for PR creation
      repository-projects: write  # Required for PR management
      statuses: write  # Required for PR status updates

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - name: Install dependencies
        run: bun install

      - name: Sync data
        run: |
          bun run sync-all

      - name: Check for changes
        id: git_status
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        id: cpr
        if: steps.git_status.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.FGPAT }}
          commit-message: 'chore: sync jetpack libraries and changelogs'
          title: 'chore: sync jetpack data'
          body: |
            Automated sync of Jetpack libraries and changelogs
            
            - Updated library groups
            - Updated changelogs
          branch: chore/sync-jetpack-data
          delete-branch: true
          labels: |
            automated
            dependencies

      - name: Enable auto-merge
        if: steps.git_status.outputs.has_changes == 'true' && steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --merge "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.FGPAT }}
